version: '3.8'
services:
  lan999-vault:
    image: python:3.11-slim
    volumes:
      - ./codex:/app/codex
      - ./psbt:/app/psbt
      - ./bitcoin:/root/.bitcoin
    environment:
      - BITCOIN_RPC_USER=landback
      - BITCOIN_RPC_PASSWORD=vault999
    command: >
      sh -c "pip install -r requirements.txt && python vault_lan999.py"
    depends_on:
      - bitcoind
    restart: unless-stopped

  bitcoind:
    image: ruimarinho/bitcoin-core:25.0
    command: -rpcuser=landback -rpcpassword=vault999 -rpcallowip=172.0.0.0/8
    volumes:
      - bitcoin-data:/root/.bitcoin
    ports:
      - "8332:8332"

volumes:
  bitcoin-data: