name: Auto-Proof on Push
on: [push]
jobs:
  proof:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with: { python-version: '3.11' }
      - run: pip install opentimestamps-client
      - run: python scripts/auto_proof.py
      - uses: actions/upload-artifact@v3
        with:
          name: bitcoin-proofs
          path: proofs/